### PR TITLE
Ft user registration

### PR DESCRIPTION
**Pull request by PhilzAce1**
# Ft-User-registration-#169151767
by Philzace1 and ibeFx
>user can register
>user input will be validated
>user will be given a token after registratio

### CODE REVIEW

**Comment by PhilzAce1** [comment]
# TO TEST
>clone the repo
>navigate to sever folder 
>run npm install 
>using postman-post using this format **{
	"username":"somethbig",
	"email": "difddbidfofa@gmaidl.com",
	"password":"cotiodfallejr"
}"**  > to the localhost:3000/api/v1/signup

**Comment by mikeattara** [comment]
Kindly add a screenshot of your test in Postman

**Comment by Emex4gman** [comment]
the post request and response 



the generated token

**Comment by PhilzAce1** [comment]
image

**Comment by PhilzAce1** [comment]
image

**Comment by PhilzAce1** [comment]
# if the user input is worng


image

**Pull request merged**
